<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovementRepository extends EntityRepository
{
    public function getIngresos($source) {
        $result = $this->getEntityManager()->createQuery(
            'SELECT m FROM AppBundle:Movement m WHERE m.amount > 0 and m.source = :source'
        )
        ->setParameter('source', $source)
        ->execute();
        return $result;
    }

    public function getGastos($source) {
        $result = $this->getEntityManager()->createQuery(
            'SELECT m FROM AppBundle:Movement m WHERE m.amount < 0 and m.source = :source'
        )
            ->setParameter('source', $source)
            ->execute();
        return $result;
    }
}
